### PR TITLE
Tyler post template all

### PR DESCRIPTION
**Pull request by tlaz4**

### CODE REVIEW

**Comment by MichaelParadis** [comment]
So things are whack right now. I recommend waiting until things are all merged before fixing the problems

**Comment by tlaz4** [comment]
Sure, I’ll just keep working and I can add to the master once everything is good, since it’s just some additional templates and views

**Comment by MichaelParadis** [comment]
@tlaz4 you should be able to pull master into this branch and remake it.

**Comment by tlaz4** [comment]
@MichaelParadis sure will do in a bit

**Pull request closed without merging**
